---
deployment:
  tasks:
    - export DEPLOYPATH="$HOME/public_html/"
    - /bin/echo "Deploying to $DEPLOYPATH"
    - /usr/bin/rsync -a --delete --exclude '.git' --exclude '.cpanel.yml' ./ "$DEPLOYPATH"
